spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:9091  # Use HTTP scheme for localhost
          predicates:
            - Path=/api/users/**
        - id: ROLES-SERVICE
          uri: http://localhost:9092  # Use HTTP scheme for localhost
          predicates:
            - Path=/api/roles/**
        - id: ATTENDANCE-SERVICE
          uri: http://localhost:9093  # Use HTTP scheme for localhost
          predicates:
            - Path=/api/attendance/**
        
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
       
server:
  port: 9090
