spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/api/users/**
        - id: ROLES-SERVICE
          uri: http://localhost:9092
          predicates:
            - Path=/api/roles/**
        - id: ATTENDANCE-SERVICE
          uri: http://localhost:9093
          predicates:
            - Path=/api/attendance/**  config:
    import: configserver:http://localhost:8585
        
server:
  port: 9090